version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=secret
            - MAIL_MAILER=smtp
            - MAIL_HOST=mailhog
            - MAIL_PORT=1025
        depends_on:
            - db
            - mailhog

    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
        volumes:
            - db_data:/var/lib/mysql

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"

volumes:
    db_data:
